---
title: "Solutions institutionnelles de déploiement d'applications shiny avec kubernetes"
author: Cédric Midoux, Pierre Neuvial, Cédric Midoux, Emily Walker 
editor: source
bibliography: refs_shiny-deployment.bib
---

# Motivation

- besoin de déploiement d'appli [shiny](https://shiny.posit.co/) pour utilisation sans programmation
- solution proposée par [shinyapps.io](https://www.shinyapps.io/): limitation à 25h/mois pour la version gratuite, et 1Gb de RAM 
- solution proposée par Posit (anciennement par Shiny Server Pro): [PositConnect](https://posit.co/products/enterprise/connect/): payant (cher)
- intérêts d'avoir une solution institutionnelle

## Outils institutionnels existants

| Outil | Institution | Références |
|-------|------|-----------|
| [plmshift](https://plmshift.pages.math.cnrs.fr/) | CNRS | |
| [SK8](https://sk8.inrae.fr/) | INRAE | @maigne:hal-04141247 |
| [Shiny-K8s](https://gitlab.pasteur.fr/hub/shiny-k8s ) | Institut Pasteur | @brancotte:pasteur-04643557 |

[plmshift](https://plmshift.pages.math.cnrs.fr/) est une plate-forme de déploiement d'applications web proposée par l'institut des maths au CNRS. Il est possible de déployer une application shiny (ainsi que de nombreux autres types d'applications web) mais cela nécessite d'apprendre à utiliser OpenShift.

## shiny + Kubernetes

Les deux autres outils ([SK8](https://sk8.inrae.fr/) et [Shiny-K8s](https://gitlab.pasteur.fr/hub/shiny-k8s)) sont dédiés au déploiement d'applications shiny via [Kubernetes](https://kubernetes.io/) (aka K8s). Ces outils sont simples d'utilisation: le développeur de l'application shiny doit fournir un dépôt git contenant le code source de l'application et spécifier les dépendances (via un fichier csv dédié pour shiny-K8s, ou automatiquement via renv pour SK8).

## Accessibilité ?

[SK8](https://sk8.inrae.fr/) et [Shiny-K8s](https://gitlab.pasteur.fr/hub/shiny-k8s) sont respectivement accessibles seulement pour des projets développés par INRAE et Institut Pasteur. 

Afin de rendre ce type d'outil accessible à une autre institution (en particulier le CNRS), on peut envisager soit l'ouverture d'un des services existants à cette institution, soit la mise à disposition de ce type de service directement par l'institution. Les deux solutions nécessitent des ressources matérielles et humaines; la première solution peut permettre des économies d'échelle mais peut poser des questions sur le partage des données de recherche entre institutions. 

## Autres ressources

- [code](https://gitlab.pasteur.fr/hub/shiny-k8s-example) d'une application démo pour déploiement avec shiny-K8s: 
- [présentation](https://forgemia.inra.fr/elisemaigne/slides/presentation_sk8_rr2024) d'Elise Maigné aux rencontres R 2024: 

## Bibliographie